#ifndef __RT_AI_IFPERSON_MODEL_H
#define __RT_AI_IFPERSON_MODEL_H

#include <ifperson.h>
#include <ifperson_data.h>

/* model info ... */

// model name
#define RT_AI_IFPERSON_MODEL_NAME			"ifperson"
#define RT_AI_IFPERSON_WORK_BUFFER_BYTES		AI_IFPERSON_DATA_ACTIVATIONS_SIZE
#define RT_AI_IFPERSON_DATA_WEIGHTS_SIZE		AI_IFPERSON_DATA_WEIGHTS_SIZE

#define RT_AI_IFPERSON_BUFFER_ALIGNMENT		AI_IFPERSON_ACTIVATIONS_ALIGNMENT

#define RT_AI_IFPERSON_IN_NUM				AI_IFPERSON_IN_NUM
#define RT_AI_IFPERSON_IN_1_SIZE				AI_IFPERSON_IN_1_SIZE
#define RT_AI_IFPERSON_IN_1_SIZE_BYTES		AI_IFPERSON_IN_1_SIZE_BYTES
#define RT_AI_IFPERSON_IN_TOTAL_SIZE_BYTES	(AI_IFPERSON_IN_1_SIZE_BYTES)
#define RT_AI_IFPERSON_IN_SIZE_BYTES			{AI_IFPERSON_IN_1_SIZE_BYTES}


#define RT_AI_IFPERSON_OUT_NUM				AI_IFPERSON_OUT_NUM
#define RT_AI_IFPERSON_OUT_1_SIZE			AI_IFPERSON_OUT_1_SIZE
#define RT_AI_IFPERSON_OUT_1_SIZE_BYTES		AI_IFPERSON_OUT_1_SIZE_BYTES
#define RT_AI_IFPERSON_OUT_TOTAL_SIZE_BYTES	(AI_IFPERSON_OUT_1_SIZE_BYTES)
#define RT_AI_IFPERSON_OUT_SIZE_BYTES		{AI_IFPERSON_OUT_1_SIZE_BYTES}


#define RT_AI_IFPERSON_TOTAL_BUFFER_SIZE		(NULL)		//unused

#endif	//end
